experiment_messages:
  font: 'Arial'
  size: 0.05
  encoding: 'ISO-8859-1'

sentence_span:
  trials:
    list_lengths: [4, 5, 6, 7, 8]
  practice:
    list_lengths: [3, 4, 5]
  timing:
    sentence: 4.0             # maximum display duration for each sentence response
  encoding: 'utf-8'
