name: wmc-battery
channels:
  - conda-forge
dependencies:
  - python=3.6
  - psychopy=2021.2.3
  - numpy
  - pandas
  - scipy
  - pytest
  - pyyaml
  - pip
  - pip:
    - psychtoolbox
    - pygame
    - pyo
    - pyparallel; platform_system != "Windows"
    - SoundFile; platform_system == "Windows"
    - websocket_client
    - dotmap
