allowed_keys:
  ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'num_0', 'num_1', 'num_2', 'num_3', 'num_4',
   'num_5', 'num_6', 'num_7', 'num_8', 'num_9']

frames:
  width: 0.266
  height: 0.25
  locations:
    2: [[-0.267, 0], [0.267, 0]]
    3: [[-0.4, 0], [0, 0], [0.4, 0]]
    4: [[-0.267, 0.1675], [0.267, 0.1675],
        [-0.267, -0.1675], [0.267, -0.1675]]
    5: [[-0.4, 0.1675], [0, 0.1675], [0.4, 0.1675],
        [-0.267, -0.1675], [0.267, -0.1675]]
    6: [[-0.4, 0.1675], [0, 0.1675], [0.4, 0.1675],
        [-0.4, -0.1675], [0, -0.1675], [0.4, -0.1675]]
  units: 'height'

practice:
  set_sizes: [2, 3]
  n_operations: [4, 3]

trials:
  set_sizes: [3, 4, 3, 4, 5, 4, 5, 3, 5, 3, 3, 5, 4, 4, 5]
  n_operations: [3, 4, 6, 5, 5, 3, 2, 2, 3, 5, 4, 4, 6, 2, 6]
  # this is only relevant for the result file.
  # changing it won't work with the R-script!
  max_set_size: 6

timing:
  init_trial: 1.0            # blank frame duration before first presentation
  digit: 1.0                 # onscreen duration of each presented digit
  operation: 1.3             # onscreen duration of each presented operation
  inter_item: 0.25           # blank frame duration between each presentation
  recall: 1.0                # onscreen duration of recalled response
  inter_trial: 1.0           # blank screen duration between each trial

text:
  font: 'Arial'
  size: 0.075
