alphabet:
    [b, c, d, f, g, h, j, k, l, m, n, p, r, s, t, v, w, x, z]

trials:
    n_trials_per_condition: 3
    # list_lengths: [4, 5, 6, 7, 8]
    list_lengths: [3, 4, 5, 6]
    shuffle: True
    # this is only relevant for the result file.
    # changing it won't work with the R-script!
    max_list_length: 8

practice:
    n_trials_per_condition: 1
    list_lengths: [2, 3, 4]
    shuffle: False

key_map:
    False: left
    True: right
